spring:
  application:
    name: grpc-http #应用名称
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181 # 用于发现服务的 zookeeper 信息 host:port
      discovery:
        register: false
  http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true
server:
  port: 8088


